# Версия API для провижининга
apiVersion: 1

# Список источников данных для создания
datasources:
  # Название источника данных. Может быть любым.
  - name: Prometheus
    # Тип источника данных. Должен быть 'prometheus'.
    type: prometheus
    # Указывает, что этот источник данных будет использоваться по умолчанию
    # в новых панелях.
    isDefault: true
    # URL нашего Prometheus сервера.
    # Так как Grafana и Prometheus находятся в одной docker-сети,
    # мы можем обращаться к нему по имени сервиса 'prometheus'.
    url: http://prometheus:9090
    # Режим доступа: 'proxy' означает, что запросы от браузера
    # к источнику данных будут идти через бэкенд Grafana.
    # Это стандартная и рекомендуемая настройка.
    access: proxy
    # Не разрешаем редактирование этого источника данных через UI,
    # чтобы все изменения шли только через код (IaC).
    editable: false
