{
 "title": "MNIST Service Dashboard",
 "tags": [ "mlops" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Скорость обработки (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(predictions_requests_total_total[5m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Латентность P95 / P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(predictions_latency_seconds_bucket[5m])) by (le, job))",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(predictions_latency_seconds_bucket[5m])) by (le, job))",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "Частота ошибок предсказания",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(predictions_errors_total[5m])) by (job)",
     "legendFormat": "Errors per second"
    }
   ]
  },
  {
   "title": "Распределение предсказанных цифр",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(predictions_class_distribution_total[5m])) by (digit)",
     "legendFormat": "Цифра {{digit}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job='mnist-ml-service'}[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area='heap', job='mnist-ml-service'}) by (job)",
     "legendFormat": "Used Heap"
    }
   ]
  },
  {
   "title": "JVM GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[1m])",
     "legendFormat": "GC Pause Time"
    }
   ]
  }
 ]
}